- name: Homepage Dir
  ansible.builtin.file:
    path: ~/docker/homepage
    state: directory

- name: Config Homepage
  ansible.builtin.template:
    src: homepage/{{ item }}.yaml
    dest: ~/docker/homepage/{{ item }}.yaml
  loop:
    - settings
    - services
    - widgets
    - docker
    - bookmarks
