- name: Traefik Dir
  ansible.builtin.file:
    path: ~/docker/traefik
    state: directory

- name: Traefik Dir
  ansible.builtin.file:
    path: /portainer/env_files/traefik
    state: directory

- name: Traefik DNS Setup
  ansible.builtin.template:
    src: traefik/config
    dest: /portainer/env_files/traefik/.env
