services:
  broker:
    image: docker.io/library/redis:8.2.0
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:17.5
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
    env_file:
      - /env_files/paperless/.env

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.17.1
    restart: unless-stopped
    container_name: paperless
    networks:
      - proxy
      - paperless
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.paper.rule=Host(`paper.home.nce.wtf`)"
      - "traefik.http.services.paper.loadbalancer.server.port=8000"
      - "traefik.http.routers.paper.entrypoints=websecure"
    depends_on:
      - db
      - broker
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - /portainer/paperless-export:/usr/src/paperless/export
      - /portainer/paperless:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_URL: https://paper.home.nce.wtf
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_CONSUMER_ENABLE_BARCODES: true
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: true
      PAPERLESS_CONSUMER_BARCODE_SCANNER: ZXING
    env_file:
      - /env_files/paperless/.env

volumes:
  data:
  media:
  pgdata:
  redisdata:

networks:
  paperless:
  proxy:
    external: true
