services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - proxy
    command:
#      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.network=proxy"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=oraclecloud"
#      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=770135+nce@users.noreply.github.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls.domains[0].main=home.nce.wtf"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.home.nce.wtf"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.proxy.rule=Host(`proxy.home.nce.wtf`)"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"
      - "traefik.http.routers.proxy.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - /env_files/traefik/.env
    secrets:
      - api_private_key
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/letsencrypt"
networks:
  proxy:
    external: true
secrets:
  api_private_key:
    file: /home/nce/docker/traefik/api_private_key.pem

